"""empty message

Revision ID: 932893b8ffb6
Revises: 954e7fb8874f
Create Date: 2025-04-29 11:42:27.129110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932893b8ffb6'
down_revision = '954e7fb8874f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bid')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isOpen', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('isOpen')

    op.create_table('bid',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('highest_bidder', sa.VARCHAR(length=100), nullable=True),
    sa.Column('is_open', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
