"""empty message

Revision ID: 954e7fb8874f
Revises: 885d16d50bb4
Create Date: 2025-04-27 21:56:43.980865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '954e7fb8874f'
down_revision = '885d16d50bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hacker_rank_points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('detected_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('detected_points')
        batch_op.drop_column('hacker_rank_points')

    # ### end Alembic commands ###
