"""Add fairness column to User mod

Revision ID: 9d9357b579cc
Revises: 3ffd1a6940dc
Create Date: 2025-04-27 17:59:20.755338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d9357b579cc'
down_revision = '3ffd1a6940dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fairness_points', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('fairness_points')

    # ### end Alembic commands ###
